/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tessocm.project;

import net.sourceforge.tess4j.ITesseract;
import net.sourceforge.tess4j.Tesseract;
import net.sourceforge.tess4j.TesseractException;
import net.sourceforge.tess4j.util.LoadLibs;

import java.io.File;

public class Library {
    public static void main(String[] args) {
        File imageFile = new File("dickens.jpg");
        ITesseract instance = new Tesseract(); // JNA Interface Mapping
        File tessDataFolder = LoadLibs.extractTessResources("tessdata"); // Maven build only; only English data bundled
        instance.setDatapath(tessDataFolder.getPath());

        try {
            String result = instance.doOCR(imageFile);
            System.out.println(result);
        } catch (TesseractException e) {
            System.err.println(e.getMessage());
        }
    }
    public boolean someLibraryMethod() {
        return true;
    }
}
