/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tessocm.project;

import net.sourceforge.tess4j.ITesseract;
import net.sourceforge.tess4j.Tesseract;
import net.sourceforge.tess4j.TesseractException;
import net.sourceforge.tess4j.util.LoadLibs;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class Library {
    public static void main(String[] args) throws IOException {
        File imageFile = new File("rotatedcc.png");
        BufferedImage b1 = ImageIO.read(imageFile);
        ITesseract instance = new Tesseract();
        File tessDataFolder = LoadLibs.extractTessResources("tessdata");
        instance.setLanguage("eng");
        instance.setDatapath(tessDataFolder.getPath());
        try {
            String result = instance.doOCR(b1);
            System.out.println(result);
        } catch (TesseractException e) {
            System.err.println(e.getMessage());
        }
    }
    public boolean someLibraryMethod() {
        return true;
    }
}
